// import lake from '../assets/images/lake.jpg';
// import campfire from '../assets/images/icons8-campfire-100.png';
// import beach from '../assets/images/icons8-beach-100.png';
// import expedition from '../assets/images/icons8-expedition-100.png';
// import spinnerLure from '../assets/images/icons8-spinner-lure-100.png';
// import beach from '../assets/images/icons8-beach-100.png';
// import aaron from '../assets/images/rsz_aaron-burden-uffiweqspd4-unsplash.jpg';
// import angela from '../assets/images/rsz_angela-onyin-u_naqvsarfm-unsplash.jpg';
// import bonnie from '../assets/images/rsz_bonnie-kittle-xbfehnamlfi-unsplash.jpg';
// import kalen from '../assets/images/rsz_kalen-emsley-mgjskgio_ji-unsplash.jpg';
// import mariah from '../assets/images/rsz_mariah-hewines-tjunv_epiy8-unsplash.jpg';
// import peter from '../assets/images/rsz_peter-thomas-vcpjwm2kjbk-unsplash.jpg';
// import musil from '../assets/images/rsz_sean-musil-ah2ofe8aqds-unsplash.jpg';
// import daniel from '../assets/images/rsz_daniel-norris-2tddnkqpv0a-unsplash.jpg';

// export const lakeImage = `<img src"${lake}"/>`;
// export const campfireImage = `<img src"${campfire}"/>`;
// export const beachImage = `<img src"${beach}"/>`;
// export const expeditionImage = `<img src"${expedition}"/>`;
// export const spinnerLureImage = `<img src"${spinnerLure}"/>`;
// export const beachImage = `<img src"${beach}"/>`;
// export const aaronImage = `<img src"${aaron}"/>`;
// export const angelaImage = `<img src"${angela}"/>`;
// export const bonnieImage = `<img src"${bonnie}"/>`;
// export const kalenImage = `<img src"${kalen}"/>`;
// export const mariahImage = `<img src"${mariah}"/>`;
// export const peterImage = `<img src"${peter}"/>`;
// export const musilImage = `<img src"${musil}"/>`;
// export const danielImage = `<img src"${daniel}"/>`;
